espectaculos:
    resource: "@EspectaculosBundle/Controller/"
    type:     annotation
    prefix:   /

tnt2017_blog:
    resource: "@Tnt2017BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"